services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpass123
      - ALLOWED_HOSTS=irrigogt.com,www.irrigogt.com,144.217.161.233,localhost

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # CAMBIO 1: Montamos la carpeta real de certificados de Certbot (como solo lectura por seguridad)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # CAMBIO 2: Mantenemos el volumen para la renovación de certificados
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

volumes:
  sqlite_data: