version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpass123
      - ALLOWED_HOSTS=irrigogt.com,www.irrigogt.com,144.217.161.233,localhost

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app/frontend_src # Evita sobreescribir nginx.conf
      - ./certbot/conf:/etc/letsencrypt # <-- AÑADIDO: Para los certificados
      - ./certbot/www:/var/www/certbot   # <-- AÑADIDO: Para la validación
    depends_on:
      - backend

volumes:
  sqlite_data: