# Generated by Django 5.2.2 on 2025-06-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='latitud',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='longitud',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
    ]
