# Generated by Django 5.2.2 on 2025-09-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensajechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='solucion',
            field=models.TextField(blank=True, help_text='Descripción de la solución aplicada por el fontanero', null=True),
        ),
    ]
