# Generated by Django 5.1.7 on 2025-04-16 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_incidencia_historialincidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fontanero', models.ForeignKey(limit_choices_to={'rol': 'FONTANERO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='incidencias.incidencia')),
            ],
        ),
    ]
